name: CI/CD Pipeline - Angular v20

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    name: Test & Build Application

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Chrome browser
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run unit tests
        run: |
          export CHROME_BIN=$(which google-chrome-stable)
          npm run test -- --watch=false --browsers=ChromeHeadlessNoSandbox
        env:
          CHROME_BIN: /usr/bin/google-chrome-stable

      - name: Run linting (optional)
        run: npm run lint || true
        continue-on-error: true

      - name: Build Angular application for production
        run: |
          REPOSITORY_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          npm run build -- --configuration=production --base-href="/$REPOSITORY_NAME/" --output-path=dist

      - name: Not found fixture
        run: |
          if [ -d "dist/browser" ]; then
            cp dist/browser/index.html dist/browser/404.html
            echo "OUTPUT_DIR=dist/browser" >> $GITHUB_ENV
          else
            cp dist/index.html dist/404.html
            echo "OUTPUT_DIR=dist" >> $GITHUB_ENV
          fi

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.OUTPUT_DIR }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    needs: test-and-build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
